### ISSUE TITLE
[FEATURE REQ] Upgrade to Godot 4.5

### ISSUE THREAD

**Issue by cengiz-pz** [godot-sdk-integrations/godot-admob#9]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Plugin depends on Godot 4.4.1.

### Proposed Behavior

Upgrade dependency to Godot 4.5.

### Godot Version

4.4.1.stable

### OS Godot Is Running On

Windows 11

### Plugin Version

4.0

### OS Plugin Is Running On

Android 14

**Comment by drifterbob** [comment]
Hi! Just testing the plugin with the 4.5 beta3 release of godot for linux.. I get an error 

07-09 13:59:24.262 24790 24790 I Ads     : Received log message: <Google:HTML> You are currently using version 250505999.250505300.1 of the SDK, which is out of date. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be installed fro...

This seems to prevent load_banner_ad from working.

Will this be addressed with this fix?

Many thanks for the hard work on this plugin!
drifterbob

**Comment by syntaxerror247** [comment]
@cengiz-pz It seems like you forgot to commit `libs.versions.toml` file.
I would say to not ignore gradle directory here: https://github.com/godot-sdk-integrations/godot-admob-plugin/blob/d589935a88858ec2fbf1c08fe19292d3887ac34e/android/.gitignore#L22
